version: 2
jobs:
  build:
    machine: true
    working_directory: ~/nginx-docker
    steps:
      - checkout
      - run:
          name: build nginx docker image
          command: |
            echo "$dockerhub_pass" | docker login -u "$dockerhub_user" --password-stdin
            docker build -t hehety/nginx:latest .
            docker push hehety/nginx:latest



workflows:
  version: 2
  build:
    jobs:
      - build